// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"
export var ContentTypeID;
(function (ContentTypeID) {
    ContentTypeID["The0X003380B11739741641A4CE5C19A7B616B5"] = "0x003380B11739741641A4CE5C19A7B616B5";
    ContentTypeID["The0X01002522DD143061454C9693B1F643DD63BB"] = "0x01002522DD143061454C9693B1F643DD63BB";
    ContentTypeID["The0X0100B81419040D1C9142AB52817377787648"] = "0x0100B81419040D1C9142AB52817377787648";
    ContentTypeID["The0X0101007955491C8658214DA701FF24370E5321"] = "0x0101007955491C8658214DA701FF24370E5321";
    ContentTypeID["The0X0101007FE5D1FCC4C0AF478EA3C2155851974A"] = "0x0101007FE5D1FCC4C0AF478EA3C2155851974A";
    ContentTypeID["The0X01200028E0799C581B764CA603DB8091653C25"] = "0x01200028E0799C581B764CA603DB8091653C25";
    ContentTypeID["The0X01200034027B036AAEB24EBAC9492575FEA1E9"] = "0x01200034027B036AAEB24EBAC9492575FEA1E9";
    ContentTypeID["The0X0120008D35AA0A40AB0B418EFDFD5F125598F7"] = "0x0120008D35AA0A40AB0B418EFDFD5F125598F7";
    ContentTypeID["The0X012000CFDBD4A265C0E04BB67064EC826EF63E"] = "0x012000CFDBD4A265C0E04BB67064EC826EF63E";
})(ContentTypeID || (ContentTypeID = {}));
export var Type;
(function (Type) {
    Type["CollectionEdmString"] = "Collection(Edm.String)";
    Type["CollectionSPTaxonomyTaxonomyFieldValue"] = "Collection(SP.Taxonomy.TaxonomyFieldValue)";
    Type["SPChangeToken"] = "SP.ChangeToken";
    Type["SPFieldURLValue"] = "SP.FieldUrlValue";
    Type["SPResourcePath"] = "SP.ResourcePath";
    Type["SPUserIDInfo"] = "SP.UserIdInfo";
})(Type || (Type = {}));
export var Direction;
(function (Direction) {
    Direction["None"] = "none";
})(Direction || (Direction = {}));
export var URL;
(function (URL) {
    URL["Layouts15ImagesItdlPNGRev47"] = "/_layouts/15/images/itdl.png?rev=47";
    URL["Layouts15ImagesItgenPNGRev47"] = "/_layouts/15/images/itgen.png?rev=47";
    URL["Layouts15ImagesItwpPNGRev47"] = "/_layouts/15/images/itwp.png?rev=47";
    URL["SitesTeamSiteDevOps"] = "/sites/TeamSite/DevOps";
})(URL || (URL = {}));
