// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface DB {
    AlphaListItems: Item[];
    BravoListItems: Item[];
    OData__x005f_catalogs_x002f_designItems: Item[];
    Shared_x0020_DocumentsItems: Item[];
    OData__x005f_catalogs_x002f_masterpageItems: ODataX005FCatalogsX002FMasterpageItem[];
    PublishedFeedListItems: PublishedFeedListItem[];
    OpsDocsItems: Item[];
    SiteAssetsItems: Item[];
    SitePagesItems: SitePagesItem[];
    SPInterfaceItems: Item[];
    CurrentUser: CurrentUser;
    Webs: Webs;
    lists: Webs;
}

export interface Item {
    __metadata: FluffyMetadata;
    FirstUniqueAncestorSecurableObject: PuneHedgehog;
    RoleAssignments: PuneHedgehog;
    AttachmentFiles: PuneHedgehog;
    ContentType: PuneHedgehog;
    GetDlpPolicyTip: PuneHedgehog;
    FieldValuesAsHtml: PuneHedgehog;
    FieldValuesAsText: PuneHedgehog;
    FieldValuesForEdit: PuneHedgehog;
    File: PuneHedgehog;
    Folder: PuneHedgehog;
    LikedByInformation: PuneHedgehog;
    ParentList: PuneHedgehog;
    Properties: PuneHedgehog;
    Versions: PuneHedgehog;
    FileSystemObjectType: number;
    Id: number;
    ServerRedirectedEmbedUri: null;
    ServerRedirectedEmbedUrl: string;
    ID: number;
    ContentTypeId: ContentTypeID;
    Title: null | string;
    Modified: string;
    Created: string;
    AuthorId: number;
    EditorId: number;
    OData__UIVersionString: string;
    Attachments?: boolean;
    GUID: string;
    OData__ColorTag: null;
    ComplianceAssetId: null;
    NewColumn1Id?: null;
    Name?: string;
    MasterPageUrl?: EURL | null;
    ThemeUrl?: EURL | null;
    ImageUrl?: EURL | null;
    FontSchemeUrl?: EURL | null;
    DisplayOrder?: number;
    MediaServiceAutoTags?: null;
    MediaServiceOCR?: null;
    OData__CopySource?: null;
    CheckoutUserId?: null;
}

export interface PuneHedgehog {
    __deferred: Deferred;
}

export interface Deferred {
    uri: string;
}

export enum ContentTypeID {
    The0X003380B11739741641A4CE5C19A7B616B5 = "0x003380B11739741641A4CE5C19A7B616B5",
    The0X01002522DD143061454C9693B1F643DD63BB = "0x01002522DD143061454C9693B1F643DD63BB",
    The0X0100B81419040D1C9142AB52817377787648 = "0x0100B81419040D1C9142AB52817377787648",
    The0X0101007955491C8658214DA701FF24370E5321 = "0x0101007955491C8658214DA701FF24370E5321",
    The0X0101007FE5D1FCC4C0AF478EA3C2155851974A = "0x0101007FE5D1FCC4C0AF478EA3C2155851974A",
    The0X01200028E0799C581B764CA603DB8091653C25 = "0x01200028E0799C581B764CA603DB8091653C25",
    The0X01200034027B036AAEB24EBAC9492575FEA1E9 = "0x01200034027B036AAEB24EBAC9492575FEA1E9",
    The0X0120008D35AA0A40AB0B418EFDFD5F125598F7 = "0x0120008D35AA0A40AB0B418EFDFD5F125598F7",
    The0X012000CFDBD4A265C0E04BB67064EC826EF63E = "0x012000CFDBD4A265C0E04BB67064EC826EF63E",
}

export interface EURL {
    __metadata: PurpleMetadata;
    Description: string;
    Url: string;
}

export interface PurpleMetadata {
    type: Type;
}

export enum Type {
    CollectionEdmString = "Collection(Edm.String)",
    CollectionSPTaxonomyTaxonomyFieldValue = "Collection(SP.Taxonomy.TaxonomyFieldValue)",
    SPChangeToken = "SP.ChangeToken",
    SPFieldURLValue = "SP.FieldUrlValue",
    SPResourcePath = "SP.ResourcePath",
    SPUserIDInfo = "SP.UserIdInfo",
}

export interface FluffyMetadata {
    id: string;
    uri: string;
    etag?: string;
    type: string;
}

export interface CurrentUser {
    d: CurrentUserD;
}

export interface CurrentUserD {
    __metadata: FluffyMetadata;
    Alerts: PuneHedgehog;
    Groups: PuneHedgehog;
    Id: number;
    IsHiddenInUI: boolean;
    LoginName: string;
    Title: string;
    PrincipalType: number;
    Email: string;
    Expiration: string;
    IsEmailAuthenticationGuestUser: boolean;
    IsShareByEmailGuestUser: boolean;
    IsSiteAdmin: boolean;
    UserId: UserID;
    UserPrincipalName: string;
}

export interface UserID {
    __metadata: PurpleMetadata;
    NameId: string;
    NameIdIssuer: string;
}

export interface ODataX005FCatalogsX002FMasterpageItem {
    __metadata: FluffyMetadata;
    FirstUniqueAncestorSecurableObject: PuneHedgehog;
    RoleAssignments: PuneHedgehog;
    AttachmentFiles: PuneHedgehog;
    ContentType: PuneHedgehog;
    GetDlpPolicyTip: PuneHedgehog;
    FieldValuesAsHtml: PuneHedgehog;
    FieldValuesAsText: PuneHedgehog;
    FieldValuesForEdit: PuneHedgehog;
    File: PuneHedgehog;
    Folder: PuneHedgehog;
    LikedByInformation: PuneHedgehog;
    ParentList: PuneHedgehog;
    Properties: PuneHedgehog;
    Versions: PuneHedgehog;
    FileSystemObjectType: number;
    Id: number;
    ServerRedirectedEmbedUri: null;
    ServerRedirectedEmbedUrl: string;
    ContentTypeId: string;
    ComplianceAssetId: null;
    MasterPageDescription: null;
    UIVersion: UIVersion;
    DefaultCssFile: null | string;
    DisplayTemplateJSTemplateHidden: null;
    DisplayTemplateJSTargetControlType: null;
    DisplayTemplateJSIconUrl: null;
    DisplayTemplateJSTemplateType: null;
    DisplayTemplateJSTargetScope: null;
    DisplayTemplateJSTargetListTemplate: null;
    OData__ColorTag: null;
    ID: number;
    Created: string;
    AuthorId: number;
    Modified: string;
    EditorId: number;
    OData__CopySource: null;
    CheckoutUserId: null;
    OData__UIVersionString: string;
    GUID: string;
}

export interface UIVersion {
    __metadata: PurpleMetadata;
    results: string[];
}

export interface PublishedFeedListItem {
    __metadata: FluffyMetadata;
    FirstUniqueAncestorSecurableObject: PuneHedgehog;
    RoleAssignments: PuneHedgehog;
    AttachmentFiles: PuneHedgehog;
    ContentType: PuneHedgehog;
    GetDlpPolicyTip: PuneHedgehog;
    FieldValuesAsHtml: PuneHedgehog;
    FieldValuesAsText: PuneHedgehog;
    FieldValuesForEdit: PuneHedgehog;
    File: PuneHedgehog;
    Folder: PuneHedgehog;
    LikedByInformation: PuneHedgehog;
    ParentList: PuneHedgehog;
    Properties: PuneHedgehog;
    Versions: PuneHedgehog;
    FileSystemObjectType: number;
    Id: number;
    ServerRedirectedEmbedUri: null;
    ServerRedirectedEmbedUrl: string;
    ContentTypeId: string;
    Title: string;
    ComplianceAssetId: null;
    MicroBlogType: null;
    PostAuthor: null;
    DefinitionId: null;
    RootPostID: null;
    RootPostOwnerID: null;
    RootPostUniqueID: null;
    ReplyCount: null;
    ReferenceID: null;
    Attributes: null;
    Content: null;
    ContentData: null;
    SearchContent: null;
    RefRoot: null;
    RefReply: null;
    PostSource: null;
    PeopleCount: null;
    PeopleList: null;
    MediaLinkType: null;
    MediaLinkDescription: null;
    PostSourceUri: null;
    MediaLinkURI: null;
    MediaLinkUISnippet: null;
    MediaLinkContentURI: null;
    MediaLength: null;
    MediaWidth: null;
    MediaHeight: null;
    MediaPreviewWidth: null;
    MediaPreviewHeight: null;
    MediaActionWidth: null;
    MediaActionHeight: null;
    MediaActionClickUrl: null;
    MediaActionClickKind: null;
    eMailSubscribers: null;
    eMailUnsubscribed: null;
    RemoteLocation: null;
    LikesCount: null;
    LikedByStringId: null;
    HashTags: UIVersion;
    OData__ColorTag: null;
    ID: number;
    Modified: string;
    Created: string;
    AuthorId: number;
    EditorId: number;
    OData__UIVersionString: string;
    Attachments: boolean;
    GUID: string;
}

export interface SitePagesItem {
    __metadata: FluffyMetadata;
    FirstUniqueAncestorSecurableObject: PuneHedgehog;
    RoleAssignments: PuneHedgehog;
    AttachmentFiles: PuneHedgehog;
    ContentType: PuneHedgehog;
    GetDlpPolicyTip: PuneHedgehog;
    FieldValuesAsHtml: PuneHedgehog;
    FieldValuesAsText: PuneHedgehog;
    FieldValuesForEdit: PuneHedgehog;
    File: PuneHedgehog;
    Folder: PuneHedgehog;
    LikedByInformation: PuneHedgehog;
    ParentList: PuneHedgehog;
    Properties: PuneHedgehog;
    Versions: PuneHedgehog;
    FileSystemObjectType: number;
    Id: number;
    ServerRedirectedEmbedUri: null;
    ServerRedirectedEmbedUrl: string;
    ContentTypeId: string;
    ComplianceAssetId: null;
    WikiField: null | string;
    Title: null;
    CanvasContent1: null;
    BannerImageUrl: null;
    Description: null;
    PromotedState: null;
    FirstPublishedDate: null;
    LayoutWebpartsContent: null;
    OData__AuthorBylineId: null;
    _AuthorBylineStringId: null;
    OData__TopicHeader: null;
    OData__SPSitePageFlags: null;
    OData__OriginalSourceUrl: null;
    OData__OriginalSourceSiteId: null;
    OData__OriginalSourceWebId: null;
    OData__OriginalSourceListId: null;
    OData__OriginalSourceItemId: null;
    OData__SPCallToAction: null;
    OData__ColorTag: null;
    ID: number;
    Created: string;
    AuthorId: number;
    Modified: string;
    EditorId: number;
    OData__CopySource: null;
    CheckoutUserId: null;
    OData__UIVersionString: string;
    GUID: string;
}

export interface Result {
    __metadata: FluffyMetadata;
    FirstUniqueAncestorSecurableObject: PuneHedgehog;
    RoleAssignments: PuneHedgehog;
    Author?: PuneHedgehog;
    ContentTypes?: PuneHedgehog;
    CreatablesInfo?: PuneHedgehog;
    DefaultView?: PuneHedgehog;
    DescriptionResource?: PuneHedgehog;
    EventReceivers?: PuneHedgehog;
    Fields?: PuneHedgehog;
    Forms?: PuneHedgehog;
    InformationRightsManagementSettings?: PuneHedgehog;
    Items?: PuneHedgehog;
    ParentWeb?: PuneHedgehog;
    RootFolder?: PuneHedgehog;
    Subscriptions?: PuneHedgehog;
    TitleResource?: PuneHedgehog;
    UserCustomActions?: PuneHedgehog;
    VersionPolicies?: PuneHedgehog;
    Views?: PuneHedgehog;
    WorkflowAssociations?: PuneHedgehog;
    AllowContentTypes?: boolean;
    BaseTemplate?: number;
    BaseType?: number;
    ContentTypesEnabled?: boolean;
    CrawlNonDefaultViews?: boolean;
    Created: string;
    CurrentChangeToken?: CurrentChangeToken;
    DefaultContentApprovalWorkflowId?: string;
    DefaultItemOpenUseListSetting?: boolean;
    Description?: string;
    Direction?: Direction;
    DisableCommenting?: boolean;
    DisableGridEditing?: boolean;
    DocumentTemplateUrl?: null | string;
    DraftVersionVisibility?: number;
    EnableAttachments?: boolean;
    EnableFolderCreation?: boolean;
    EnableMinorVersions?: boolean;
    EnableModeration?: boolean;
    EnableRequestSignOff?: boolean;
    EnableVersioning?: boolean;
    EntityTypeName?: string;
    ExemptFromBlockDownloadOfNonViewableFiles?: boolean;
    FileSavePostProcessingEnabled?: boolean;
    ForceCheckout?: boolean;
    HasExternalDataSource?: boolean;
    Hidden?: boolean;
    Id: number | string;
    ImagePath?: Path;
    ImageUrl?: URL;
    DefaultSensitivityLabelForLibrary?: string;
    SensitivityLabelToEncryptOnDOwnloadForLibrary?: null;
    IrmEnabled?: boolean;
    IrmExpire?: boolean;
    IrmReject?: boolean;
    IsApplicationList?: boolean;
    IsCatalog?: boolean;
    IsPrivate?: boolean;
    ItemCount?: number;
    LastItemDeletedDate?: string;
    LastItemModifiedDate?: string;
    LastItemUserModifiedDate?: string;
    ListExperienceOptions?: number;
    ListItemEntityTypeFullName?: string;
    MajorVersionLimit?: number;
    MajorWithMinorVersionsLimit?: number;
    MultipleDataList?: boolean;
    NoCrawl?: boolean;
    ParentWebPath?: Path;
    ParentWebUrl?: URL;
    ParserDisabled?: boolean;
    ServerTemplateCanCreateFolders?: boolean;
    TemplateFeatureId?: string;
    Title: string;
    d?: WebsD;
    data?: Webs;
    AttachmentFiles?: PuneHedgehog;
    ContentType?: PuneHedgehog;
    GetDlpPolicyTip?: PuneHedgehog;
    FieldValuesAsHtml?: PuneHedgehog;
    FieldValuesAsText?: PuneHedgehog;
    FieldValuesForEdit?: PuneHedgehog;
    File?: PuneHedgehog;
    Folder?: PuneHedgehog;
    LikedByInformation?: PuneHedgehog;
    ParentList?: PuneHedgehog;
    Properties?: PuneHedgehog;
    Versions?: PuneHedgehog;
    FileSystemObjectType?: number;
    ServerRedirectedEmbedUri?: null;
    ServerRedirectedEmbedUrl?: string;
    ContentTypeId?: ContentTypeID;
    OData__ColorTag?: null;
    ComplianceAssetId?: null;
    NewColumn1Id?: null;
    ID?: number;
    Modified?: string;
    AuthorId?: number;
    EditorId?: number;
    OData__UIVersionString?: string;
    Attachments?: boolean;
    GUID?: string;
}

export interface WebsD {
    results: Result[];
}

export interface Webs {
    Title: string;
    EntityTypeName(EntityTypeName: any, listItems: any[]): unknown;
	DELETE(dataId: number): unknown;
    PATCH(id: number, data: any): unknown;
    PUT(arg0: { Id: number; Title: string; }): unknown;
    GET(queryString?: string): any[];
    POST(arg0: { Title: string; }): unknown;
    Id: any;
    d: WebsD;
}

export interface CurrentChangeToken {
    __metadata: PurpleMetadata;
    StringValue: string;
}

export enum Direction {
    None = "none",
}

export interface Path {
    __metadata: PurpleMetadata;
    DecodedUrl: URL;
}

export enum URL {
    Layouts15ImagesItdlPNGRev47 = "/_layouts/15/images/itdl.png?rev=47",
    Layouts15ImagesItgenPNGRev47 = "/_layouts/15/images/itgen.png?rev=47",
    Layouts15ImagesItwpPNGRev47 = "/_layouts/15/images/itwp.png?rev=47",
    SitesTeamSiteDevOps = "/sites/TeamSite/DevOps",
}
